# Copyright 2019 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

cc_test(
    name = "basic_test",
    srcs = ["basic_test.cc"],
    deps = ["//url"],
)
