# Copyright 2019 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

cc_library(
    name = "polyfills",
    hdrs = [
        "base/base_export.h",
        "base/component_export.h",
        "base/debug/alias.h",
        "base/export_template.h",
        "base/logging.h",
        "base/trace_event/memory_usage_estimator.h",
    ],
    visibility = ["//visibility:public"],
)
